### ISSUE TITLE
Comments to Z80 tools

### ISSUE THREAD

**Issue by rottensnow** [maccasoft/z80-tools#1]
1. The mac version: The menu items <Z80 Tools\About Z80 Tools> and <Z80 Tools\Preferences> do not work. These items can be selected in other parts of the menu system.

2. When assembling/compiling; upon detection of errors; a cryptic error message is produced.
How can I decrypt the error messages? 
Suggest: report line number and descriptive error messages.

**Comment by maccasoft** [comment]
>     1. The mac version: The menu items <Z80 Tools\About Z80 Tools>
>     and <Z80 Tools\Preferences> do not work. These items can be selected
>     in other parts of the menu system.

Where are located these items ? I don't have a Mac to test so I don't know if there are misplaced menu items, these should be located under the Help and File menu drop-down respectively. Are they located somewhere else ? If possible attach a small image that shows the issue.

>     2. When assembling/compiling; upon detection of errors; a cryptic error message
>     is produced.
>        How can I decrypt the error messages?
>        Suggest: report line number and descriptive error messages.

The console view should display the error messages in red prefixed with the file name, line number and column (if applicable) in a gcc-like style, clicking on the error message should move the editor to the affected line in the source. What error message you see ?

**Comment by rottensnow** [comment]
Regarding menu items, the enclosed picture should be self-explanatory, the menu items working and not working are indicated.
![screen shot 2019-01-15 at 11 42 41](https://user-images.githubusercontent.com/46672606/51177285-77d86000-18bf-11e9-9b34-ec3a1cb47e46.png)

Thanks for clarifying about the error reporting.
![screen shot 2019-01-15 at 12 24 49](https://user-images.githubusercontent.com/46672606/51177689-9854ea00-18c0-11e9-94ad-dd1089c7913e.png)
I think the error is caused by invalid statement.

**Comment by maccasoft** [comment]
I have updated the Mac OS-X package with some changes that should fix the menu issue: now the Z80 Tools menu items should work as expected, and the duplicated items in the File menu are removed. The Help menu is no longer displayed as the only item is not shown anymore.
